# Generated by Django 2.2.12 on 2020-09-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
