# Generated by Django 2.2.12 on 2020-07-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='logo_F',
        ),
    ]
