# Generated by Django 2.2.12 on 2020-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_siteinfo_logo_f'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseau_social',
            new_name='Reseau',
        ),
        migrations.AlterModelOptions(
            name='reseau',
            options={'verbose_name': 'Reseau', 'verbose_name_plural': 'Reseaux'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
