# Generated by Django 2.2.12 on 2020-07-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200703_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseau_social',
            new_name='Reseau',
        ),
        migrations.AlterModelOptions(
            name='reseau',
            options={'verbose_name': 'Reseau', 'verbose_name_plural': 'Reseaux'},
        ),
    ]
