# Generated by Django 2.2.12 on 2020-07-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200702_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date_add',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immage/gallery')),
                ('date_add', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_gallery', to='blog.Lieu')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallerys',
            },
        ),
    ]
