# Generated by Django 2.2.12 on 2020-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200703_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
