# Generated by Django 2.2.12 on 2020-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_event_speackers'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
